# This is an appspec.yml template file for use with AWS CodeDeploy.
# The lines in this template starting with the hashtag symbol are 
#   instructional comments and can be safely left in the file or 
#   ignored.
# For help completing this file, see the "AppSpec File Reference" in the  
#   "AWS CodeDeploy User Guide" at
#   http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux
files:
  -
    source: something.py
    destination: /home/ubuntu/something.py

  -
    source: requirements.txt
    destination: /home/ubuntu/requirements.txt
hooks:
  BeforeInstall:
    - 
      location: scripts/BeforeInstallS3.sh
      runas: root
    - 
      location: scripts/BeforeInstallAgainS3.sh
      runas: root
  AfterInstall:
    - 
      location: scripts/AfterInstallS3.sh
      runas: root